version: '3'

services:
  web:
    image: abdullahmafuz1/btre
    command: >
        bash -c "python manage.py migrate
        && python manage.py create_super_user
        && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
        - db
  db:
    image: postgres
    environment: 
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=btredb