# Generated by Django 3.0.6 on 2020-05-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='eamil',
            new_name='email',
        ),
    ]
